### ISSUE TITLE
Failed to fetch cluster metadata from zookeeper @/stream/metadata

### ISSUE THREAD

**Issue by rolish** [apache/bookkeeper#2084]
**QUESTION**
I'm trying to use streams with bookkeeper gprc.
Configmap:
```
## Credits to Franck Cuny : https://github.com/fcuny/distributedlog-on-k8s/blob/master/bookkeeper.statefulset.yaml
apiVersion: v1
kind: ConfigMap
metadata:
    name: bookie-config
data:
    BK_BOOKIE_EXTRA_OPTS: "\"-Xms1g -Xmx1g -XX:MaxDirectMemorySize=1g -XX:+UseG1GC  -XX:MaxGCPauseMillis=10 -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions -XX:+AggressiveOpts -XX:+DoEscapeAnalysis -XX:ParallelGCThreads=32 -XX:ConcGCThreads=32 -XX:G1NewSizePercent=50 -XX:+DisableExplicitGC -XX:-ResizePLAB\""
    BK_bookiePort: "3181"
    BK_journalDirectory: "/bookkeeper/data/journal"
    BK_ledgerDirectories: "/bookkeeper/data/ledgers"
    BK_indexDirectories: "/bookkeeper/data/ledgers"
#    BK_zkServers: "zookeeper-1.cgiallpayments.com"
    BK_metadataServiceUri: "zk://zookeeper-1.x.com;zookeeper-2.x.com;zookeeper-3.x.com;zookeeper-4.x.com;zookeeper-5.x.com;zookeeper-6.x.com/ledgers"
    BK_httpServerEnabled: "true"
    BK_httpServerPort: "8080"
    # TODO: Issue 458: https://github.com/apache/bookkeeper/issues/458
    #BK_statsProviderClass: org.apache.bookkeeper.stats.prometheus.PrometheusMetricsProvider
    # use hostname as bookie id as bookie statefulset runs with hostnetwork: true
    BK_useHostNameAsBookieID: "false"
    BOOKIE_GRPC_PORT: "4181"
    BK_extraServerComponents: org.apache.bookkeeper.stream.server.StreamStorageLifecycleComponent
```
version:
```
image: apache/bookkeeper:4.9.1
```
Getting startup exception:
```
Exception in thread "main" org.apache.bookkeeper.stream.storage.exceptions.StorageRuntimeException: Failed to fetch cluster metadata from zookeeper @/stream/metadata
```
Attaching full log of bookie-0:

[logs-from-bookie-in-bookie-0 (18).txt](https://github.com/apache/bookkeeper/files/3146021/logs-from-bookie-in-bookie-0.18.txt)
